### ISSUE TITLE
requirements.txt used for bqml_ga4_gaming_propensity_to_churn.ipynb example needed

### ISSUE THREAD

**Issue by jimwill3** [GoogleCloudPlatform/analytics-componentized-patterns#57]
Hi, I've tried quite a few permutations of google-cloud-bigquery, google-cloud-bigquery-storage, pyrarrow, google-cloud-core, and google-api-core without any success in making queries to bigquery. I've gotten grpc errors, then client_credential missing attribute errors, and so on. is there a requirements.tx showing what versions of packages were used to run the sample? the particular sample is: bqml_ga4_gaming_propensity_to_churn.ipynb 
thanks,
jim

**Comment by jimwill3** [comment]
Hi,
AI Platform notebooks - Tensorflow 2.3 build.(fresh instance created 30 minutes before running this notebook)
!sudo pip install google-cloud-bigquery
#restart kernel


from google.cloud import bigquery
import pandas as pd

pd.set_option('display.float_format', lambda x: '%.3f' % x)
print(bigquery.__version__)
>>2.13.1

%%bigquery --project $PROJECT_ID

SELECT * FROM  `firebase-public-project.analytics_153293282.events_*` TABLESAMPLE SYSTEM (1 PERCENT)

>>AttributeError: 'ClientOptions' object has no attribute 'credentials_file'

after about 2 hours of searching around I found this suggested workaround on stackoverflow:
!sudo /opt/conda/bin/conda install -c conda-forge google-cloud-bigquery google-cloud-bigquery-storage pandas pyarrow --yes
!pip install google-cloud-bigquery

restart the kernel - code now works.
thanks,
jim

________________________________

**Comment by polong-lin** [comment]
Thanks for following up and with your solution! I'll add it to the notebook for future users who may run into the same issue.
