### ISSUE TITLE
Dataset not Available

### ISSUE THREAD

**Issue by Joshuacourse** [GoogleCloudPlatform/analytics-componentized-patterns#61]
The public firebase-public-project.analytics_153293282.events_20181003 dataset is no longer available in the BigQuery

**Comment by Joshuacourse** [comment]
It looks like the project firebase-public-project is taken off the shelf.

**Comment by polong-lin** [comment]
Hi Joshua, thanks for reporting this. We are currently investigating and will update this issue when it's fixed.

**Comment by polong-lin** [comment]
Hi, sorry for the delay in responding but the dataset should be up and available again.
