### ISSUE TITLE
which user identifier to use

### ISSUE THREAD

**Issue by Joshuacourse** [GoogleCloudPlatform/analytics-componentized-patterns#65]
In the notebook, I saw "In our analysis, we used user_pseudo_id as the user identifier. However, ideally, your app should send back the user_id from your app to Google Analytics."  I have a few questions:
Is user_pseudo_id automatically enabled? 
If I am using Google Analytics data only (no other 1st party data) for model building and audience activation is via Google Ads, DV360, or SA360 (no CRM), user_id is not necessary, am I assuming correctly?

**Comment by minhaz** [comment]
`user_pseudo_id` is always available in the GA4 dataset. Here's [more info](https://support.google.com/analytics/answer/9213390) on this.

**Comment by Joshuacourse** [comment]
Hi Minhaz, thank you for sharing. The link you shared does not mention user_pseudo_id. I am trying to connect the user_pseudo_id column in the BigQuery data to the UI concept.  Did I miss anything?

**Comment by minhaz** [comment]
In GA4 BigQuery dataset, the `user_id` column is what you(i.e. developer) sends back to GA as `user id` with each hit. If you don't send back anything, this will be blank. `user_pseudo_id` is generated by GA based on user identity and is automatically filled in. The link above explains how the user identity is determined.

**Comment by Joshuacourse** [comment]
Hi Google team, if I would like to identify high-intent users in Google Analytics and activate them via DV360 custom bidding. Should I use user data import or a GA goal?

**Comment by Joshuacourse** [comment]
Hi Google team, GA already has a conversion probability report under Audience > Behavior > Conversion Probability. What is the added value of doing modeling with raw data?
